config/routes.rb
StudioBelleFiori::Application.routes.draw do
  root to: 'Main#home'

  match '/salao', to: 'main#salao'
  match '/looks', to: 'main#looks'
  match '/esmalteria', to: 'main#esmalteria'
  match '/estetica', to: 'main#estetica'
  match '/noivas', to: 'main#noivas'
  match '/contato', to: 'main#contato'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def home
  end

  def salao
  end

  def looks
  end

  def esmalteria
  end

  def estetica
  end

  def noivas
  end

  def contato
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <address>
    <strong>Studio Belle Fiori Cabeleireiros e Comércio Ltda.</strong><br>
    Av. Marechal Tito, 2185 - 1&ordm Andar<br>
    São Paulo - SP - 08022-000<br>
    <abbr title="Telefone">Tel.</abbr> (11) 2025-8320
  </address>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="navbar container-fluid upper-bar-padding">
		<div class="navbar-inner">
			<div class="row-fluid">
			  <div class="span4">
			  	<%= link_to image_tag("studiobellefiori.png", alt: "Studio Belle Fiori", class:"brand"), root_path, id: "logo" %>
			  </div>
			  <div class="span8">
			  	<div class="row-fluid">
			  		<div class="pull-right social-networks-padding">
						<%= link_to image_tag("facebook_small.png", alt: "Facebook", id:"facebook_link"), 
							'http://www.facebook.com/StudioBelleFiori', target: "_blank" %>
						<%= link_to image_tag("twitter_small.png", alt: "Twitter", id:"twitter_link"), 
							'http://www.twitter.com/', target: "_blank" %>
						<%= link_to image_tag("youtube_small.png", alt: "YouTube", id:"youtube_link"), 
							'http://www.youtube.com/studiobellefiori', target: "_blank" %>
					</div>
			  	</div>
			  	<div class="row-fluid menu">
						<nav>
							<ul class="nav pull-right">
								<li><%= link_to "Salão", salao_path %></li>
								<li><%= link_to "Looks", looks_path %></li>
								<li><%= link_to "Esmalteria", esmalteria_path %></li>
								<li><%= link_to "Estética", estetica_path %></li>
								<li><%= link_to "Noivas", noivas_path %></li>
								<li><%= link_to "Contato", contato_path %></li>
							</ul>
						</nav>
			  	</div>
			  </div>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Studio Belle Fiori - Cabelo &amp; Estética</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= favicon_link_tag 'favicon.ico' %>
		<%= javascript_include_tag 'bootstrap-carousel.js' %>
		<%= javascript_include_tag 'bootstrap-transition.js' %>
		<%= javascript_include_tag 'carousel.js' %>
		<%= javascript_include_tag 'social-networks-links.js' %>
		<div class="container">
			<%= render 'layouts/header' %>
		</div>
		<div class="container">
			<div class="center hero-unit">
				<%= yield %>
			</div>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/main/contato.html.erb
<h1>Contato e Localização</h1>

<p>
  <address>
    Av. Marechal Tito, 2185 - 1&ordm Andar<br>
    São Paulo - SP - 08022-000<br>
    <abbr title="Telefone">Tel.</abbr> (11)2025-8320<br>
    E-Mail: <a href="mailto:contato@studiobellefiori.com.br">contato@studiobellefiori.com.br</a>
  </address>
</p>

<iframe class="map"
	src="http://maps.google.com.br/maps?f=q&amp;source=s_q&amp;hl=pt-BR&amp;geocode=&amp;q=Avenida+Marechal+Tito,+2185,+S%C3%A3o+Paulo&amp;aq=0&amp;oq=av.+marechal+tito,+2185&amp;sll=-23.717468,-46.595764&amp;sspn=0.771979,1.167297&amp;ie=UTF8&amp;hq=&amp;hnear=Av.+Mal.+Tito,+2185+-+Vila+Curu%C3%A7%C3%A1,+S%C3%A3o+Paulo,+08022-000&amp;ll=-23.494328,-46.424624&amp;spn=0.003021,0.00456&amp;t=m&amp;z=14&amp;output=embed">
</iframe>

<small>
	<a href="http://maps.google.com.br/maps?f=q&amp;source=embed&amp;hl=pt-BR&amp;geocode=&amp;q=Avenida+Marechal+Tito,+2185,+S%C3%A3o+Paulo&amp;aq=0&amp;oq=av.+marechal+tito,+2185&amp;sll=-23.682803,-46.595546&amp;sspn=0.772188,1.167297&amp;ie=UTF8&amp;hq=&amp;hnear=Av.+Mal.+Tito,+2185+-+Vila+Curu%C3%A7%C3%A1,+S%C3%A3o+Paulo,+08022-000&amp;t=m&amp;ll=-23.494343,-46.424618&amp;spn=0.037783,0.054932&amp;z=14&amp;iwloc=A", target="_blank">Ampliar Mapa</a>
</small>

app/views/main/esmalteria.html.erb
<h1>Esmalteria</h1>
<br>

<div class="row">

	<div class="span6 salao-text">
		<p>
			Página em desenvolvimento...
		</p>
	</div>

	<div class="span5">
		<%= image_tag("nails2.jpg", alt: "Unhas coloridas", class: "images") %>
	</div>
	
</div>

app/views/main/estetica.html.erb
<h1>Estética</h1>
<br>

<div class="row">

	<div class="span6 salao-text">
		<p>
			Página em desenvolvimento...
		</p>
	</div>

	<div class="span5">
		<%= image_tag("esthetics2.jpg", alt: "Execução de serviços de estética", class: "images") %>
	</div>
	
</div>

app/views/main/home.html.erb
<div id="carrossel" class="carousel slide">

  <!-- Carousel items -->
  <div class="carousel-inner">

    <div class="active item">
    	<%= image_tag("blonde_hair.jpg", alt: "Loira com cabelo encaracolado") %>
    </div>

    <div class="item">
    	<%= image_tag("afro_hair.jpg", alt:"Morena com cabelo afro") %>
    </div>

    <div class="item">
    	<%= image_tag("wedding.jpg", alt:"Noiva") %>
				<!-- <div class="carousel-caption">
    		<h4>Dia da Noiva</h4>
    	</div> -->
    </div>

    <div class="item">
    	<%= image_tag("makeup.jpg", alt:"Maquiagem") %>
    </div>

    <div class="item">
    	<%= image_tag("nails.jpg", alt:"Unhas") %>
    </div>

    <div class="item">
    	<%= image_tag("esthetics.jpg", alt:"Estética") %>
    </div>

  </div>
  		<!-- Carousel nav -->
			<!-- 	  <a class="carousel-control left" href="#carrossel" data-slide="prev">&lsaquo;</a>
  		<a class="carousel-control right" href="#carrossel" data-slide="next">&rsaquo;</a> -->
</div>

<!-- 	<br><br>

<h2>Testando elementos para o site</h2><br><br>
<div class="post-it">
	<h2>Teste de Post-it</h2>
	<ul>
		<li>* foo</li>
		<li>* bar</li>
	</ul>
</div>

<br><br>
-->

app/views/main/looks.html.erb
<h1>Looks</h1>
<br>

<div class="row">

	<div class="span6 salao-text">
		<p>
			Em breve você poderá conferir nesta seção as imagens de clientes antes e após a realização de serviços como
			corte, escova, progressiva, luzes, coloração, penteado, maquiagem, entre outros.
		</p>
	</div>

	<div class="span5">
		<%= image_tag("makup2.jpg", alt: "Maquiagem", class: "images") %>
	</div>
	
</div>

app/views/main/noivas.html.erb
<h1>Noivas</h1>
<p>Página em desenvolvimento...</p>

app/views/main/salao.html.erb
<h1>Salão</h1>
<br>

<div class="row">

	<div class="span6 salao-text">
		<p>
			O Studio Belle Fiori traz para São Miguel Paulista o que há de mais moderno em técnicas e equipamentos para a área de beleza e estética, prezando sempre pela qualidade dos serviços prestados e seguindo rigorosamente as normas de higiene e esterilização.
		</p>
		<p>
			Em uma área de 300m&sup2, o cliente encontrará um ambiente confortável e sofisticado, que conta com ampla sala de espera, 
			uma aconchegante lanchonete, área de esmalteria (manicure e pedicure), espaço para corte e lavatórios e salas para realização dos serviços de podologia, depilação, estética corporal e facial.
		</p>
		<p>
			Já para as noivas foi criado um espaço exclusivo, com total conforto e privacidade, para que esse momento tão especial seja realizado em grande estilo.
		</p>
	</div>

	<div class="span5">
		<%= image_tag("salon2.png", alt: "Serviços do Salão", class: "images") %>
	</div>
	
</div>